//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesment8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public string Name { get; set; }
        public string House { get; set; }
        public string Allegiance { get; set; }
        public string Book { get; set; }
        public string EmailAddress { get; set; }
    }
}
